### ISSUE TITLE
这个YouhuayoujianfangfangzhiProcedure似乎会导致打火石点不了蜡烛、放置方块没声音

### ISSUE THREAD

**Issue by Dave12138** [PrimogemStudio/Primogem-Craft#1]
玩别的mod做了个药水蜡烛，发现打火石点不了，同时放置方块也没声音、机械动力的强力胶用不了。
按住shift对着箱子放方块还是会打开箱子的GUI还算意料之中，但让主手物品抢夺类附魔失效就很诡异了（
排查了一会后发现传送到其他维度或者重新进入存档都能解决，拿祈愿之杖右键一下稳定触发这个bug。
我是觉得就是这个修改建造权的锅，因为储物囊也会触发这个bug。
“不会是因为客户端不知道我恢复行动能力了吧，没进行同步？”

**Comment by PepperMO** [comment]
已修复，感谢反馈
